build: src/main/Main.java src/grammar/Adverb.java src/grammar/Article.java src/grammar/Conjunction.java src/grammar/Noun.java src/grammar/Phrase.java src/grammar/Preposition.java src/grammar/Sentence.java src/grammar/Verb.java src/grammar/Word.java src/parser/Parser.java src/statics/Dictionary.java
	javac -d bin src/*/*.java
run: bin/main/Main.class bin/grammar/Adverb.class bin/grammar/Article.class bin/grammar/Conjunction.class bin/grammar/Noun.class bin/grammar/Phrase.class bin/grammar/Preposition.class bin/grammar/Sentence.class bin/grammar/Verb.class bin/grammar/Word.class bin/parser/Parser.class bin/statics/Dictionary.class
	java -classpath bin main.Main
